// Generated by CoffeeScript 1.9.2
(function() {
  var i, item, len, liHeight, ref;

  liHeight = $(window).height() / 6;

  ref = $('.menu ul').find('li');
  for (i = 0, len = ref.length; i < len; i++) {
    item = ref[i];
    $(item).height(liHeight).css('padding-top', $(window).height() / 12 - 14 + 'px');
  }

}).call(this);


//# sourceMappingURL=main.js.map
