// Generated by CoffeeScript 1.9.2
(function() {
  var i, item, len, liHeight, menuItems;

  menuItems = $('.menu ul').find('li');

  liHeight = $(window).height() / menuItems.length;

  for (i = 0, len = menuItems.length; i < len; i++) {
    item = menuItems[i];
    $(item).height(liHeight).width(liHeight).css('padding-top', $(window).height() / 12 - 14 + 'px');
  }

}).call(this);


//# sourceMappingURL=main.js.map
